-- No seed data needed: core-service's remaining features (quotes, sessions) don't own any JPA
-- entities that need real rows here. The instruments seed data this file used to hold moved to
-- buy-sell-service's src/test/resources/data.sql along with the Instrument/Order entities.
