-- 006: Market simulation (BR-08, BR-12, BR-13; service expectation 9.1)
--
-- Prices are generated by the backend's Geometric Brownian Motion (GBM) simulator
-- (com.lemarketjames.market). This migration adds what that simulator needs:
--
--   1. Three more US equities (AMZN, TSLA, NVDA) so every quoted symbol is also a
--      real instrument that orders and holdings can reference.
--   2. instrument_market_params: per-instrument settings that control how a price moves.
--   3. market_quotes becomes a "latest price" snapshot (one row per instrument) so
--      prices survive a backend restart instead of resetting.
--   4. price_candles: 1-minute OHLC history for charts and reporting.
--
-- IDEMPOTENT: Safe to run more than once. On a fresh Docker volume Postgres runs this
-- file automatically, and CI (Jenkinsfile) applies it again afterwards.
--
-- Existing instrument ids (1 = AAPL, 2 = MSFT, 3 = GOOGL) are never renumbered: CI relies
-- on id 3 being the non-tradable instrument.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Additional instruments
-- ---------------------------------------------------------------------------
INSERT INTO instruments (ticker, name, asset_class, currency, tradable, location) VALUES
    ('AMZN', 'Amazon.com Inc', 'EQUITY', 'USD', TRUE, 'US'),
    ('TSLA', 'Tesla Inc',      'EQUITY', 'USD', TRUE, 'US'),
    ('NVDA', 'NVIDIA Corp',    'EQUITY', 'USD', TRUE, 'US')
ON CONFLICT (ticker) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Simulation parameters (one row per instrument)
-- ---------------------------------------------------------------------------
-- Kept in a separate table rather than on `instruments` so the simulation can be
-- tuned (or removed in favour of a real market data feed) without touching the
-- instrument master record that orders and holdings depend on.
CREATE TABLE IF NOT EXISTS instrument_market_params (
    instrument_id       INTEGER PRIMARY KEY REFERENCES instruments(instrument_id),
    initial_price       NUMERIC(14,4) NOT NULL CHECK (initial_price > 0),  -- starting price when no snapshot exists
    drift               NUMERIC(8,6)  NOT NULL,                            -- mu: expected annual return, e.g. 0.08 = +8%/yr
    volatility          NUMERIC(8,6)  NOT NULL CHECK (volatility > 0),     -- sigma: annualised volatility, e.g. 0.25 = 25%/yr
    market_correlation  NUMERIC(5,4)  NOT NULL DEFAULT 0.5
                        CHECK (market_correlation BETWEEN 0 AND 1),       -- how strongly it moves with the overall market
    spread_bps          NUMERIC(8,4)  NOT NULL DEFAULT 2 CHECK (spread_bps >= 0), -- bid/ask spread in basis points
    shares_outstanding  BIGINT,                                            -- for market cap; NULL for FX/crypto
    avg_daily_volume    BIGINT        NOT NULL CHECK (avg_daily_volume >= 0),
    earnings_per_share  NUMERIC(14,4),                                     -- for P/E ratio; NULL when not meaningful
    dividend_per_share  NUMERIC(14,4) NOT NULL DEFAULT 0                   -- annual dividend, for dividend yield
);

-- Initial prices for AAPL/MSFT/GOOGL match the mid prices of existing seeded fills so
-- seeded holdings do not show a large artificial gain or loss on first start.
INSERT INTO instrument_market_params (
    instrument_id, initial_price, drift, volatility, market_correlation, spread_bps,
    shares_outstanding, avg_daily_volume, earnings_per_share, dividend_per_share)
SELECT i.instrument_id, v.initial_price, v.drift, v.volatility, v.market_correlation, v.spread_bps,
       v.shares_outstanding, v.avg_daily_volume, v.earnings_per_share, v.dividend_per_share
FROM (VALUES
    ('AAPL',  227.5500, 0.080000, 0.250000, 0.6500, 1.5, 15200000000,  55000000,  6.7500, 1.0000),
    ('MSFT',  429.8500, 0.090000, 0.230000, 0.6500, 1.5,  7430000000,  22000000, 12.1000, 3.3200),
    ('GOOGL', 175.3000, 0.090000, 0.280000, 0.6000, 2.0, 12300000000,  25000000,  7.5400, 0.8000),
    ('AMZN',  197.1500, 0.100000, 0.320000, 0.6000, 2.0, 10500000000,  40000000,  5.5300, 0.0000),
    ('TSLA',  244.2000, 0.100000, 0.550000, 0.4500, 3.0,  3200000000,  85000000,  2.0400, 0.0000),
    ('NVDA',  131.8000, 0.120000, 0.480000, 0.5500, 2.0, 24500000000, 250000000,  2.9400, 0.0400)
) AS v (ticker, initial_price, drift, volatility, market_correlation, spread_bps,
        shares_outstanding, avg_daily_volume, earnings_per_share, dividend_per_share)
JOIN instruments i ON i.ticker = v.ticker
ON CONFLICT (instrument_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. market_quotes: latest price snapshot, one row per instrument
-- ---------------------------------------------------------------------------
-- Keep only the most recent row per instrument before enforcing uniqueness.
DELETE FROM market_quotes older
USING market_quotes newer
WHERE older.instrument_id = newer.instrument_id
  AND (older.last_updated, older.quote_id) < (newer.last_updated, newer.quote_id);

ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS last_price     NUMERIC(14,4);
ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS open_price     NUMERIC(14,4);
ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS high_price     NUMERIC(14,4);
ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS low_price      NUMERIC(14,4);
ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS previous_close NUMERIC(14,4);
ALTER TABLE market_quotes ADD COLUMN IF NOT EXISTS volume         BIGINT NOT NULL DEFAULT 0;

-- Backfill pre-existing seed rows from their bid/ask mid price.
UPDATE market_quotes SET last_price     = ROUND((bid_price + ask_price) / 2, 4) WHERE last_price     IS NULL;
UPDATE market_quotes SET open_price     = last_price                            WHERE open_price     IS NULL;
UPDATE market_quotes SET high_price     = last_price                            WHERE high_price     IS NULL;
UPDATE market_quotes SET low_price      = last_price                            WHERE low_price      IS NULL;
UPDATE market_quotes SET previous_close = last_price                            WHERE previous_close IS NULL;

ALTER TABLE market_quotes ALTER COLUMN last_price     SET NOT NULL;
ALTER TABLE market_quotes ALTER COLUMN open_price     SET NOT NULL;
ALTER TABLE market_quotes ALTER COLUMN high_price     SET NOT NULL;
ALTER TABLE market_quotes ALTER COLUMN low_price      SET NOT NULL;
ALTER TABLE market_quotes ALTER COLUMN previous_close SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_market_quotes_instrument ON market_quotes (instrument_id);

-- ---------------------------------------------------------------------------
-- 4. price_candles: 1-minute OHLC history
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS price_candles (
    instrument_id   INTEGER       NOT NULL REFERENCES instruments(instrument_id),
    interval_start  TIMESTAMP     NOT NULL,  -- UTC start of the 1-minute interval
    open_price      NUMERIC(14,4) NOT NULL,
    high_price      NUMERIC(14,4) NOT NULL,
    low_price       NUMERIC(14,4) NOT NULL,
    close_price     NUMERIC(14,4) NOT NULL,
    volume          BIGINT        NOT NULL,
    PRIMARY KEY (instrument_id, interval_start)
);

COMMIT;
